import os
import random
name = input("Enter Your Name: ")
print("Hello there, " + name)
print("Three thousand years ago, a monster known as the 'El Malvado' arose in modern-day Spain. The monster terrorized the small town of Besalú.  The monster would roam the streets at night and would disappear in the morning.") 
input("Press ENTER to continue")
print("One day, the villagers decided that they've had enough. They made a deal with a monster: The villagers would deliver one human every day to El Malvado, and in exchange, El Malvado would never leave his lair, a cave near the edge of town.") 
print("Since then, the population of Besalú has been at a drastic decline. Only you can stop this monster once and for all.") 
input("Press ENTER to continue")
os.system("clear")
print("You embark on your quest to slay El Malvado. But first, you must purchase plane tickets to Belasú. Your current location is 200 miles away. Your account balance in $1000 at the moment.")

print("-------------------------------------------------------------")
print("[1]  Buy $416 Plane Ticket    [2] Buy $19 Plane Ticket")
print("-------------------------------------------------------------")
choice_1 = input()
if choice_1 == "1": 
	print("You put your safety first and buy the more expensive plane ticket. Your account balance is now $584. You make it to Belasú in one piece and continue your adventure.")
	input("Press ENTER to continue")
	print("-------------------------------------------------------------")
	print("After a few miles of walking from the closest airport in Girona, you realize that you don't exactly know where the monster is located. It's time to go to the locals!!")
elif choice_1 == "2":
	print("You decide to put your wealth over your safety and choose the $19 plane ticket. Your account balance is now $981. Bad move. The plane crashes into the Mediterranean Sea and you drown.")
	exit("YOU DIED BEFORE YOUR ADVENTURE STARTED... JUST HOW")

print("-------------------------------------------------------------")
print("[1]  Talk to merchant    [2] Talk to blacksmith")
print("-------------------------------------------------------------")
choice_2 = input()
if choice_2 == "1": 
	print("Merchant: Oh, El Malvado?? It lives just went of El Monasterio de Sant Pere. Are tú trying to slay the criatura repugnante?")
	print("You: *nods*")
	print("Merchant: I wish you the best of luck. Take this $20 bill and buy yourself something, you deserve it.")
	print("Your account balance is now $604")
	input("Press ENTER to continue")
	print("-------------------------------------------------------------")
	print("You follow the merchant's instructions and locate the cave of El Malvado. You soon realize that you are unarmed and unprepared. Another merchant comes up to you with an offer.")
	print("-------------------------------------------------------------")
	print("[1]  Purchase Dark Steel Blade ($600)    [2] Decline")
	print("-------------------------------------------------------------")
	choice_3 = input()
	if choice_3 == "1": 
		print("You purchase the Dark Steel Blade. Your account balance is now $4.")
		print("-------------------------------------------------------------")
		print("You enter the cavem now armed. You equip your new blade, but all of a sudden, your hand starts to melt.")
		print("-------------------------------------------------------------")
	print("[1]  Drop the Dark Steel Blade    [2] Keep on holding the Dark Steel Blade")
	print("-------------------------------------------------------------")
	choice_5 = input()
	if choice_5 == "1":
			print("You drop the blade and it falls into a pit. Being your only weapon, you jump into the pit to try retrieving it.")
			exit("YOU SHATTERED ALL OF YOUR BONES ")
	elif choice_5 == "2":
			print("You hold onto the sword. The sword and your hand merge into one. Does this make you an amputee?")
			input("Press ENTER to continue")
			print("-------------------------------------------------------------")
			print("You finally reach the inner core of the monster's lair. You tiptoe inside... only to notice that the monster is nowhere to be seen. It's behind you. You were the sacrifice.")
			print("-------------------------------------------------------------")
			print("[1]  Run for your life    [2] Fight the monster")
			print("-------------------------------------------------------------")
			choice_6 = input()
			if choice_6 == "1":
				print("As fast as you can, you sprint out of the cave.")
				print("-------------------------------------------------------------")
				print("Okay, slight issue here. You were the town's sacrifice. The deal between the villagers and the monster was that they'd deliver 1 sacrifice every day if the monster stopped harming them. With no sacrifice, the deal is broken.") 
				input("Press ENTER to continue")
				print("The monster decimates the town, unleashes hundreds of years' worth of pain. However, this puts too much strain on the monster and it perishes. You are the sole survivor")
				input("Press ENTER to continue")
				os.system("clear")
				print("YOU'VE WON, BUT AT WHAT COST")
				print("")
				print("")
				print("")
				print("")
				print("thank you for playing")
				
			elif choice_6 == "2":
				print("You may be brave, but you aren't strong enough to defeat El Malvado.")
				exit("YOU ARE EATEN ALIVE BY THE MONSTER")
	elif choice_3 == "2":
		print("You decline the offer and go into the cave unarmed.")
		print("-------------------------------------------------------------")
		print("You enter the cave. Unfortunately, you do not make it out of alive.")
		exit("YOU DIED DUE TO A LACK OF REASONING")
elif choice_2 == "2":
	print("Blacksmith: Oh, El Malvado?? He lives just went of El Monasterio de Sant Pere. Are tú trying to slay the criatura repugnante?")
	print("You: *nods*")
	print("Blacksmith: I wish you the best of luck. Take this sword, it will help you in combat.")
	print("You have acquired: *Bronze Greatsword* ")
	input("Press ENTER to continue")
	print("-------------------------------------------------------------")
	print("You follow the blacksmith's instructions and locate the lair of El Malvado. Suddenly, a merchant comes up to you with an offer.")
	print("-------------------------------------------------------------")
	print("[1]  Purchase Dark Steel Blade ($600)    [2] Decline")
	print("-------------------------------------------------------------")
	choice_4 = input()
	if choice_4 == "1": 
		print("Sorry, you can't afford this. Your current balance is $584.")
	elif choice_4 == "2":
		print("You declined the offer.")
	print("-------------------------------------------------------------")
	print("You finally arrive at the lair of El Malvado. At the entrance, you see the skeletal remains of many who've come before you.")
	print("Once you reach El Malvado, you've surprised to see that he his sleeping.")
	print("You try sneaking up on him for a surprise attack, but you don't look at your surroundings and fall into a ditch. You shatter all of your bones.")
	print("-------------------------------------------------------------")
	exit("YOU DIED OF BLOOD LOSS; CHOOSE A DIFFERENT PATH")